GET http://localhost:5197/games

### this is to separate requests

GET http://localhost:5197/games/8

###
POST http://localhost:5197/games
Content-Type: application/json 

{
  "name": "Advernture Game",
  "genreId": 1,
  "price": 59.99,
  "releaseDate": "2023-10-01"
}
### important to leave 1 space after content type

PUT http://localhost:5197/games/2
Content-Type: application/json 

{
  "name": "Updated Game!!!",
  "genre": "Action",
  "price": 49.99,
  "releaseDate": "2023-11-01"
}

###

DELETE http://localhost:5197/games/1